### ISSUE TITLE
Page Title Match Url

### ISSUE THREAD

**Issue by keroger2k** [keroger2k/aqjewels#50]
The URL for each piece of jewelry should have specific information in it.  I would suggest having the Page Title match the URL.  You can do this by changing the very top description in the backend.  For example:

http://www.corneaugoldsmithing.com/jewelry/c1029pms/  (this is very SEO unfriendly)

consider:

http://www.corneaugoldsmithing.com/jewelry/18k-opal-diamond-earrings  (or something like this.)

**Comment by aquiggle** [comment]
Is this okay?  

C1015EDM - Sterling Silver & Yellow Gold Earrings with Sugalite Cabochons and Pink Tourmaline

**Comment by aquiggle** [comment]
Nothing special about gold rhodolite necklace that i'm aware. :-(
